### ISSUE TITLE
Create sensor description for ITRI Bus

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/sample_sensor_kit_launch#47]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Create sensor description of ITRI Bus for simulation.

### Purpose

Sensor configuration is needed to drive ITRI bus in a simulator.

### Possible approaches

Create sensor_description and sensor_launch package for ITRI

### Definition of done

- [ ] create sensors.xacro for ITRI bus
- [ ] create sensing.launch.xml (or sensing.launch.py) for ITRI bus

**Comment by WJaworskiRobotec** [comment]
1. Provide LiDAR TF information as follows:
````
## [dx(m), dy(m), dz(m), roll(rad), pitch(rad), yaw(rad)] ##
Left to BaseLink: [0.524, 1.187, -2.134, -0.004, 0.03, 0.959]
Right to BaseLink:[0.524, -1.089, -2.108, 0.05, 0.01, -1.007]
Top to BaseLink: [0, 0, 0, 0.023, 0.21, 0]
````
2. Here is a ROSBAG link for your reference.
https://1drv.ms/u/s!AnJ4ubRnmXsujMprOuLlNkKNxosvnQ?e=BsOSZA

**Comment by WJaworskiRobotec** [comment]
https://github.com/autowarefoundation/itri_bus_sensor_kit

**Comment by WJaworskiRobotec** [comment]
Should be moved to https://github.com/autowarefoundation/awf_reference_sensor_kit_launch

**Comment by WJaworskiRobotec** [comment]
To write an issue in the repository that it does not currently support ouster drviers

**Comment by amadeuszsz** [comment]
@mitsudome-r 
Can we close this issue since https://github.com/autowarefoundation/itri_bus_sensor_kit.git has already been developed?

**Comment by amadeuszsz** [comment]
Closing as solved.
