### ISSUE TITLE
missing dependency of nebula_sensor_driver

### ISSUE THREAD

**Issue by felixf4xu** [autowarefoundation/sample_sensor_kit_launch#80]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

`nebula_sensor_driver` is a dependency, but rosdep can't find it.

### Expected behavior

When running `rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO`, rosdep can install all dependencies

### Actual behavior

>ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
common_sensor_launch: Cannot locate rosdep definition for [nebula_sensor_driver]

### Steps to reproduce

rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

### Versions

ubuntu 22
humble

autoware git main branch

**Comment by amadeuszsz** [comment]
@felixf4xu 
I guess you already solved this issue long time ago but just a comment for clarification:
Nebula is not available on ROS build farm yet, thus it is necessary to build from sources. You can pull repository with [VCS tool](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/#how-to-set-up-a-workspace).
